repoURL: https://github.com/jhhwang4195/numble-k8s-monitoring

apps:
  - name: nginx
    namespace: default
  - name: eck-operator
    namespace: elastic
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jqPathExpressions:
          - .webhooks[]?.clientConfig.caBundle
  - name: eck-elasticsearch
    namespace: elastic
  - name: eck-kibana
    namespace: elastic
  - name: eck-beats
    namespace: elastic
  - name: logstash
    namespace: elastic
  - name: kube-prometheus-stack
    namespace: prometheus    
